name: Fetch Yahoo News to AWS

on:
  schedule:
    - cron: '20,45 * * * *'  # Run at 15 minutes and 45 minutes every hour

jobs:
  fetch-rss:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Fetch Yahoo News RSS feeds
        run: |
          current_month=$(date +'%Y%m')
          current_week=$(date +'%Y%m_%W') # 1-51
          day_offset=$(( 7 - current_day_of_week ))
          current_time=$(date +'%Y%m%d_%H%M')
          folder_name="xml-files_${current_week}"
          mkdir -p $folder_name
          sleep 3
          curl -o "${folder_name}/top-picks_${current_time}.xml" https://news.yahoo.co.jp/rss/topics/top-picks.xml
          # ... (same as before)
          curl -o "${folder_name}/science_${current_time}.xml" https://news.yahoo.co.jp/rss/topics/science.xml

      - name: Set Git Config
        run: |
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
        working-directory: ${{ github.workspace }}
        
      - name: Set up AWS CLI
        run: |
          curl "https://d1vvhvl2y92vvt.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
          aws --version

      - name: Copy files to AWS S3
        run: |
          current_week=$(date +'%Y_%U') # Format as YYYY_WW
          folder_name="xml-files_202308_32"
          aws s3 cp ./${folder_name} s3://xml-topix-all --recursive
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-northeast-1"
