name: Fetch Yahoo News RSS Feed and Upload to AWS S3

on:
  schedule:
    - cron: '0,20,40 * * * *'  # Run 3 times every hour

jobs:
  fetch-and-upload:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: "ap-northeast-1"

    steps:
      # ロンドン時間で現在の日付からyyyymmを動的に設定
      - name: Extract yyyymm and week number from Current Date in GMT
        run: |
          echo "yyyymm=$(date +'%Y%m' --utc)" >> $GITHUB_ENV
          echo "week_number=$(date +'%U' --utc)" >> $GITHUB_ENV

      # Fetch the RSS feeds and upload directly to S3
      - name: Fetch Yahoo News RSS feeds and Upload to S3
        run: |
          current_week=$(date +'%Y%m_%W') # 1-51
          current_time=$(date +'%Y%m%d_%H%M')
          for topic in top-picks domestic world business entertainment sports it local science
          do
            sleep 3
            curl -o "${topic}_${current_time}.xml" "https://news.yahoo.co.jp/rss/topics/${topic}.xml"
            aws s3 cp "${topic}_${current_time}.xml" "s3://xml-topix-all/${{ env.yyyymm }}/xml-files_${current_week}/${topic}_${current_time}.xml" --storage-class ONEZONE_IA
            rm "${topic}_${current_time}.xml" # Optional: remove the file after upload
          done
