name: Fetch Yahoo News All RSS Feed

on:
  schedule:
    - cron: '0,30 * * * *'  # Run at 0 minutes and 30 minutes

jobs:
  fetch-rss:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Fetch Yahoo News RSS feeds
        run: |
          current_time=$(date +'%Y%m%d_%H%M')
          mkdir -p xml-files
          sleep 3
          curl -o "xml-files/top-picks_${current_time}_$(date +'%H%M').xml" https://news.yahoo.co.jp/rss/topics/top-picks.xml
          sleep 3
          curl -o "xml-files/domestic_${current_time}_$(date +'%H%M').xml" https://news.yahoo.co.jp/rss/topics/domestic.xml
          sleep 3
          curl -o "xml-files/world_${current_time}_$(date +'%H%M').xml" https://news.yahoo.co.jp/rss/topics/world.xml
          sleep 3
          curl -o "xml-files/business_${current_time}_$(date +'%H%M').xml" https://news.yahoo.co.jp/rss/topics/business.xml
          sleep 3
          curl -o "xml-files/entertainment_${current_time}_$(date +'%H%M').xml" https://news.yahoo.co.jp/rss/topics/entertainment.xml
          sleep 3
          curl -o "xml-files/sports_${current_time}_$(date +'%H%M').xml" https://news.yahoo.co.jp/rss/topics/sports.xml
          sleep 3
          curl -o "xml-files/it_${current_time}_$(date +'%H%M').xml" https://news.yahoo.co.jp/rss/topics/it.xml
          sleep 3
          curl -o "xml-files/local_${current_time}_$(date +'%H%M').xml" https://news.yahoo.co.jp/rss/topics/local.xml
          sleep 3
          curl -o "xml-files/science_${current_time}_$(date +'%H%M').xml" https://news.yahoo.co.jp/rss/topics/science.xml

      - name: Commit and push XML files
        run: |
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add xml-files/
          git commit -m "Update XML files"
          git push
